name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: akhil-anand
          outputs: dist/snake.svg?palette=github-dark
          # Snake grows in length as it eats commits
          # These settings are optional but recommended for smoother visuals
          color_snake: "#39FF14"
          color_dots: "#00BFFF,#FF4500,#FFD700,#ADFF2F,#FF69B4"
          snake_animation_duration: 50
          snake_length: 10 # initial length
          snake_growth: 2 # increase per eaten dot
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
