name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: akhil-anand13
          outputs: dist/snake.svg?palette=github-dark

      - name: Create output branch if it doesn't exist
        run: |
          git fetch origin
          if ! git ls-remote --exit-code --heads origin output; then
            git checkout --orphan output
            git reset --hard
            git commit --allow-empty -m "Initial output branch"
            git push origin output
          fi

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



